formula1_extended:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES_USER', 'formula1') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'formula1') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'formula1') }}"
      schema: "{{ env_var('POSTGRES_ANALYTICS_SCHEMA', 'analytics') }}"
      threads: 4
