name: formula1_extended
version: 1.0.0
config-version: 2

profile: formula1_extended

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  formula1_extended:
    +materialized: view
    marts:
      +materialized: table
