version: 2

models:
  - name: stg_sessions
    columns:
      - name: session_key
        tests:
          - not_null
          - unique

  - name: stg_drivers
    columns:
      - name: session_key
        tests:
          - not_null
      - name: driver_number
        tests:
          - not_null

  - name: stg_laps
    columns:
      - name: session_key
        tests:
          - not_null
      - name: lap_number
        tests:
          - not_null

  - name: session_driver_lap_summary
    columns:
      - name: session_key
        tests:
          - not_null
      - name: driver_number
        tests:
          - not_null
